### PR TITLE
Refactor parsing into separate file

### PR DESCRIPTION
**Pull request by ErnstHaagsman**
Hi! 

I'd like to use your parsing functionality in a different script I'm building. By refactoring it like this I can import the parsing functionality separately.

Of course, if it doesn't work for you, feel free to reject.

Thanks!

### CODE REVIEW

**Review by Ghostbird — CHANGES_REQUESTED** [review]
I think you'd want to rethink this a bit. Currently there's a weird split going on, where the `main.ts` executes code that's quite vendor specific, but defines a few vendor agnostic functions, and imports a lot of vendor specific functions.

You've moved the `Entry` class to `ing.ts`, but it's still the input to `entryToCsvLine`. You'll have to decide whether to reuse that class, and consider `entryToCsvLine` vendor agnostic, or whether that function should be in `ing.ts`.

csvStringAmount is vendor agnostic, but currently depends on vendor specific default arguments. You'll probably have to remove the defaults, or hard-code them.

writeOut and readInput are pretty much vendor agnostic as is.

Your main.ts from line 48 down contains the `querySelectorAll` which is completely ING specific.

I think you'd best:
- Evaluate the points above
- Move the ING specific stuff, including the main executed code to `ing.ts` and update the README to reflect that you should run that file to parse ING credit card statements.
- Move the vendor specific stuff to an auxiliary file that's not called `main.ts`.
- `main.ts` is now empty and can be deleted.
- Then you can write your own vendor specific file similar to `ing.ts` and execute that.

**Comment by Ghostbird** [comment]
My comment is based on the idea that you'd want to reuse the vendor agnostic part. If you want to reuse the ING specific stuff, stlll do the stuff above, but keep _only_ line 48+ in `main.ts`, don't rewrite the README.md.

**Comment by ErnstHaagsman** [comment]
Thanks for looking at my PR this quickly! 

Let me elaborate a little bit: I'm writing a script to import ING credit card transactions into [Actual](https://github.com/actualbudget/actual). So I care about the ING specific bits, and I think it'd be great to have those in one place in order to not need to duplicate work when they inevitably change their HTML. 

To break your current script into parts, it does the following:

1. Read the ING HTML file
2. Parse it into an array of `Entry` objects
3. Format the `Entry` objects into a CSV file

Part 2 is the part I'm interested in reusing directly. 

I was a bit hasty with the PR, so I guess I could've done a better job with the refactoring :) 

My consuming code looks like this right now, duplicating the `querySelectorAll` bit:

```
    const transactions = parse(fs.readFileSync("ing-cc.html"))
        .querySelectorAll(`[data-tag-name="ing-ow-expandable-item"]`)
        .map(elementToEntry)
```

I haven't really done any TypeScript development (and it's been a while since I did anything big in JS), so I'm not quite sure what the best way to build this API would be. But in pseudocode I'd really want something along the lines of: 

```
parseStatement(string htmlInput) -> Array<Entry>
```

Let me know your thoughts, I'd be happy to improve my PR.

**Comment by Ghostbird** [comment]
@ErnstHaagsman I've taken your code and refactored it a bit further. Does the current set-up work for you?

**Comment by ErnstHaagsman** [comment]
Yes! That looks amazing! Thank you so much!

**Comment by ErnstHaagsman** [comment]
Just to document this for anyone else trying to call this from JavaScript, if you get an error that looks like:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<path>\out\currency' imported from <path>\out\ing.js
```

You need to use https://github.com/barhun/extensionless. 

`--experimental-specifier-resolution=node` [no longer works.](https://github.com/nodejs/node/issues/41087#issuecomment-988203306)

**Comment by Ghostbird** [comment]
That's kind of odd. I'd expect `tsc` to compile this to clean and runnable javascript. That's after all what `tsx` does.

**Comment by ErnstHaagsman** [comment]
I would absolutely expect the same, and apparently a lot of others do to: https://github.com/microsoft/TypeScript/issues/16577
 
It looks like what they recommend is doing the import in the `*.ts` files to the (non-existent) `*.js` files?

**Comment by Ghostbird** [comment]
I've read it, and somewhat understand why they don't. Does it help if you run a bundler like `esbuild` on the resulting entry file?

**Comment by ErnstHaagsman** [comment]
I just added extensionless and added it to the npm script section in my package.json, everything is good on my side

**Pull request closed without merging**
